export enum Routes {
  INDEX = "/",
  USE_STATE = "/use-state",
  USE_EFFECT = "/use-effect",
  USE_CONTEXT = "/use-context",
  USE_REDUCER = "/use-reducer",
  USE_CALLBACK = "/use-callback",
  USE_MEMO = "/use-memo",
  USE_REF = "/use-ref",
  USE_IMPERATIVE_HANDLE = "/use-imperative-handle",
  USE_LAYOUT_EFFECT = "/use-layout-effect",
  USE_DEBUG_VALUE = "/use-debug-value",
  USE_DEFERRED_VALUE = "/use-deferred-value",
  USE_TRANSITION = "/use-transition",
  USE_ID = "/use-id",
  USE_SYNC_EXTERNAL_STORE = "/use-asyn-external-store",
  USE_INSERTION_EFFECT = "/use-insertion-effect",
}